import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
	algorithm: [
		{
			type: "autogenerated",
			dirName: "algorithm",
		},
	],
	design: [
		{
			type: "autogenerated",
			dirName: "design",
		},
	],
	community: [
		{
			type: "autogenerated",
			dirName: "community",
		},
	],
	philosophy: [
		{
			type: "autogenerated",
			dirName: "philosophy",
		},
	],
	react: [
		{
			type: "autogenerated",
			dirName: "react",
		},
	],
};

export default sidebars;
